Repository ulaval/modul, pull requests merged in 2019-10, with the labels that each got.

#67 Fix largeur et hauteur du phonefield
  packages/modul-components/src/components/phonefield/phonefield.html
  packages/modul-components/src/components/phonefield/phonefield.scss
Labels: bug fix

#63 Dropdown: AEL-598 - Ignorer la case et accent du filtre sur close
  packages/modul-components/src/components/dropdown/dropdown.ts
Labels: enhancement

#72 Fix arrow direction on Open any type on watch
  packages/modul-components/src/components/multi-select/multi-select.scss
  packages/modul-components/src/components/multi-select/multi-select.ts
Labels: bug fix

#68 Change max-length default validator behavior to ongoing
  packages/modul-components/src/utils/form/validators/max-length/max-length.ts
  src/storybook/src/modul-components/components/form/__snapshots__/form.stories.ts.snap
  src/storybook/src/modul-components/components/form/form.stories.ts
  src/storybook/src/modul.ts
Labels: breaking change, enhancement

#76 Ajouter tous les types alignements
  packages/modul-components/src/components/table/table.html
  packages/modul-components/src/components/table/table.scss
  packages/modul-components/src/components/table/table.ts
  src/storybook/src/modul-components/components/table/__snapshots__/table.stories.ts.snap
  src/storybook/src/modul-components/components/table/table.stories.ts
Labels: breaking change

#22 MODUL-1071 - MAJ Froala version 3.x
  packages/modul-components/package.json
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.html
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.scss
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.spec.ts
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.ts
  packages/modul-components/src/components/rich-text-editor/rich-text-editor-options.ts
  packages/modul-components/src/components/rich-text-editor/rich-text-editor.sandbox.html
  packages/modul-components/src/components/rich-text-editor/rich-text-editor.sandbox.ts
  packages/modul-components/src/components/rich-text-editor/rich-text-editor.spec.ts
  packages/modul-components/src/components/rich-text-editor/rich-text-editor.ts
  packages/modul-components/src/styles/mixins/_rte-internal.scss
  packages/modul-components/src/styles/mixins/_rte-theme.scss
  src/storybook/src/modul-components/components/rich-text-editor/rich-text-editor.sandbox.html
  src/storybook/src/modul-components/components/rich-text-editor/rich-text-editor.sandbox.ts
  yarn.lock
Labels: breaking change

#78 Feature/ena2 7770 ajout clear value m select
  packages/modul-components/src/components/icon-button/icon-button.html
  packages/modul-components/src/components/icon-button/icon-button.ts
  packages/modul-components/src/components/multi-select/multi-select.api.fr.json
  packages/modul-components/src/components/select/base-select/base-select.ts
  packages/modul-components/src/components/select/select.api.fr.json
  packages/modul-components/src/components/select/select.html
  packages/modul-components/src/components/select/select.scss
  packages/modul-components/src/components/select/select.ts
  src/storybook/src/modul-components/components/phonefield/__snapshots__/phonefield.stories.ts.snap
  src/storybook/src/modul-components/components/select/__snapshots__/select.stories.ts.snap
  src/storybook/src/modul-components/components/select/select.stories.ts
Labels: enhancement

#82 MMultiSelect: Éviter de faire des mutations directement sur le model
  packages/modul-components/src/components/multi-select/multi-select.ts
Labels: bug fix

#89 Correctifs d'alignement du m-table
  packages/modul-components/src/components/table/__snapshots__/table.spec.ts.snap
  packages/modul-components/src/components/table/table.html
  packages/modul-components/src/components/table/table.scss
  src/storybook/src/modul-components/components/table/__snapshots__/table.stories.ts.snap
  src/storybook/src/modul-components/components/table/table.stories.ts
Labels: bug fix

#103 Retirer les styles par default de safari
  packages/modul-components/src/components/searchfield/searchfield.scss
Labels: bug fix

#102 Tooltip: Ajout d'une prop pour pouvoir changer l'icône
  packages/modul-components/src/components/tooltip/tooltip.html
  packages/modul-components/src/components/tooltip/tooltip.ts
  src/storybook/src/modul-components/components/tooltip/__snapshots__/tooltip.stories.ts.snap
  src/storybook/src/modul-components/components/tooltip/tooltip.stories.ts
Labels: enhancement

#101 M-Popper - Fix click outside behavior and transition
  packages/modul-components/src/components/popper/popper.html
  packages/modul-components/src/components/popper/popper.ts
  src/storybook/src/modul-components/components/popper/__snapshots__/popper.stories.ts.snap
  src/storybook/src/modul-components/components/popper/popper.stories.ts
Labels: bug fix

#95 Retourner un icône m-svg__*
  packages/modul-components/src/components/icon/icon.ts
Labels: bug fix

#93 Fix accordeon open all reactivity
  packages/modul-components/src/components/accordion-group/accordion-group.html
  packages/modul-components/src/components/accordion-group/accordion-group.ts
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-disabled.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-enabled.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-open-all.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-opened-ids.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-secondary-content.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/accordion-group-disabled.stories.ts
  src/storybook/src/modul-components/components/accordion-group/accordion-group-enabled.stories.ts
  src/storybook/src/modul-components/components/accordion-group/accordion-group-open-all.stories.ts
  src/storybook/src/modul-components/components/accordion-group/accordion-group-opened-ids.stories.ts
  src/storybook/src/modul-components/components/accordion-group/accordion-group-secondary-content.stories.ts
  src/storybook/src/modul-components/components/accordion-group/accordion-group.stories.ts
  src/storybook/src/modul-components/components/accordion/__snapshots__/accordion.stories.ts.snap
  src/storybook/src/modul-components/components/accordion/accordion.stories.ts
Labels: bug fix

#45 MODUL-1074 - correction styles navbar
  packages/modul-components/src/components/navbar/navbar-item/navbar-item.scss
  packages/modul-components/src/components/navbar/navbar.scss
  packages/modul-components/src/components/navbar/navbar.ts
  src/storybook/src/modul-components/components/navbar/__snapshots__/navbar.sandbox.stories.ts.snap
  src/storybook/src/modul-components/components/navbar/__snapshots__/rich-text-editor.sandbox.stories.ts.snap
  src/storybook/src/modul-components/components/navbar/navbar.sandbox.html
  src/storybook/src/modul-components/components/navbar/navbar.sandbox.stories.ts
  src/storybook/src/modul-components/components/navbar/navbar.sandbox.ts
Labels: breaking change, enhancement

#99 MRadioGroup focus management
  packages/modul-components/src/components/radio-group/radio-group.html
  packages/modul-components/src/components/radio-group/radio-group.ts
  packages/modul-components/src/components/radio/radio.html
  packages/modul-components/src/components/radio/radio.ts
  src/storybook/src/modul-components/components/radio-group/__snapshots__/radio-group.stories.ts.snap
  src/storybook/src/modul-components/components/radio-group/radio-group.stories.ts
  src/storybook/src/modul-components/components/radio/__snapshots__/radio.stories.ts.snap
Labels: enhancement

#90 MForm: Protection de initialValue contre une reférence à une non primitive
  packages/modul-components/src/utils/form/form-contols.spec.ts
  packages/modul-components/src/utils/form/form-control.ts
Labels: bug fix

#107 fix dropdown selection problem
  packages/modul-components/src/components/popper/popper.html
Labels: bug fix

#85 Ajout d'options au RTE
  packages/modul-components/package.json
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.scss
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.ts
  packages/modul-components/src/components/rich-text-editor/rich-text-editor-options.ts
  packages/modul-components/src/components/rich-text-editor/rich-text-editor.spec.ts
  packages/modul-components/src/components/rich-text-editor/rich-text-editor.ts
  packages/modul-components/src/styles/mixins/_rte-internal.scss
  src/storybook/src/modul-components/components/rich-text-editor/rich-text-editor.sandbox.html
  src/storybook/src/modul-components/components/rich-text-editor/rich-text-editor.sandbox.ts
  yarn.lock
Labels: breaking change, enhancement

#111 Feature/modul 1200 epurer address
  packages/modul-components/src/components/address/address-lookup-field/address-lookup-field.ts
  src/storybook/src/modul-components/components/address/address-lookup-field/address-lookup-field.stories.ts
Labels: enhancement

#109 Ajout class sur les td
  packages/modul-components/src/components/table/table.html
  src/storybook/src/modul-components/components/table/__snapshots__/table.stories.ts.snap
  src/storybook/src/modul-components/components/table/table.stories.ts
Labels: breaking change

#110 Feature/ena2 8192_drag&drop
  packages/modul-components/src/directives/sortable/sortable.ts
  packages/modul-components/src/styles/mixins/_drag-and-drop.scss
  packages/modul-components/src/styles/mixins/_mixins.scss
  src/storybook/src/modul-components/components/drag-and-drop/__snapshots__/sortable.stories.ts.snap
  src/storybook/src/modul-components/components/drag-and-drop/sortable.sandbox.html
  src/storybook/src/modul-components/components/drag-and-drop/sortable.sandbox.ts
  src/storybook/src/modul-components/components/drag-and-drop/sortable.stories.ts
Labels: enhancement

#94 add parameter for default rich-text-editor size
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.html
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.ts
  packages/modul-components/src/components/rich-text-editor/rich-text-editor.html
  packages/modul-components/src/components/rich-text-editor/rich-text-editor.ts
  src/storybook/src/modul-components/components/rich-text-editor/rich-text-editor.sandbox.html
Labels: breaking change, enhancement
