Repository ulaval/modul, pull requests merged in 2019-12, with the labels that each got.

#163 [m-inplace-edit] Enlever velop en trop
  packages/modul-components/src/components/inplace-edit/inplace-edit.html
Labels: bug fix

#116 Feature/modul as a distribution prise #2!
  README.md
  packages/modul-components/.babelrc
  packages/modul-components/.browserslistrc
  packages/modul-components/conf/webpack.base.js
  packages/modul-components/conf/webpack.config.js
  packages/modul-components/conf/webpack.lib.js
  packages/modul-components/jest.config.js
  packages/modul-components/package.json
  packages/modul-components/src/components/accordion-group/accordion-group.spec.ts
  packages/modul-components/src/components/accordion/accordion.spec.ts
  packages/modul-components/src/components/components-plugin.ts
  packages/modul-components/src/components/dropdown/dropdown.spec.ignore.ts
  packages/modul-components/src/components/dynamic-template/dynamic-template.spec.ignore.ts
  packages/modul-components/src/components/flex-template/flex-template.spec.ignore.ts
  packages/modul-components/src/components/index.ts
  packages/modul-components/src/components/limit-text/limit-text.spec.ts
  packages/modul-components/src/components/scroll-top/scroll-top.spec.ts
  packages/modul-components/src/components/status/status.spec.ignore.ts
  packages/modul-components/src/components/step/step.spec.ignore.ts
  packages/modul-components/src/components/steppers/steppers.spec.ignore.ts
  packages/modul-components/src/components/switch/switch.spec.ignore.ts
  packages/modul-components/src/components/transitions/opacity-transition/opacity-transition.scss
  packages/modul-components/src/components/validation-message/validation-message.ts
  packages/modul-components/src/directives/directives-plugin.ts
  packages/modul-components/src/directives/drag-and-drop/drag-and-drop-plugin.ts
  packages/modul-components/src/directives/drag-and-drop/draggable/draggable-allow-scroll.ts
  packages/modul-components/src/directives/drag-and-drop/draggable/draggable.spec.ts
  packages/modul-components/src/directives/drag-and-drop/draggable/draggable.ts
  packages/modul-components/src/directives/drag-and-drop/droppable/droppable.spec.ts
  packages/modul-components/src/directives/index.ts
  packages/modul-components/src/directives/sortable/sortable.spec.ts
  packages/modul-components/src/filters/filters-plugin.ts
  packages/modul-components/src/filters/index.ts
  packages/modul-components/src/lang/index.ts
  packages/modul-components/src/lib.ts
  packages/modul-components/src/utils/form/index.ts
  packages/modul-components/src/utils/form/validators/index.ts
  packages/modul-components/src/utils/index.ts
  packages/modul-components/src/utils/polyfills.ts
  packages/modul-components/src/utils/polyfills/drag-and-drop.polyfill.ts
  packages/modul-rich-text-editor/.htmlhintrc
  packages/modul-rich-text-editor/.jshintrc
  packages/modul-rich-text-editor/.npmignore
  packages/modul-rich-text-editor/.stylelintrc
  packages/modul-rich-text-editor/LICENSE
  packages/modul-rich-text-editor/README.md
  packages/modul-rich-text-editor/jest.config.js
  packages/modul-rich-text-editor/package_json.ignore
  packages/modul-rich-text-editor/tests/jest/ci-test-processor.js
  packages/modul-rich-text-editor/tests/jest/jest-ignore.js
  packages/modul-rich-text-editor/tests/jest/vue-template-transformer.js
  packages/modul-rich-text-editor/tsconfig.json
  src/modul-website/src/main.ts
  src/modul-website/src/modul.ts
  src/storybook/src/modul.ts
  yarn.lock
Labels: breaking change

#153 [f-m-date] Fixer l'erreur de formatage de l'heure pour fr-CA.
  packages/modul-components/src/filters/date/time/time.ts
Labels: bug fix

#155 [svg] Ajout de nouveaux icônes
  packages/modul-components/src/assets/icons/sprites-default.svg
  src/modul-website/src/components/icon-gallery/icon-gallery-list.ts
Labels: enhancement

#156 [m-photo-editor] Correction création image sur edge
  packages/modul-components/src/components/photo-editor/crop-image/crop-image.ts
Labels: bug fix

#158 [m-expendable-layout] Ajout prop overContent dans le m-expendable-layout
  packages/modul-components/src/components/expandable-layout/expandable-layout.html
  packages/modul-components/src/components/expandable-layout/expandable-layout.scss
  packages/modul-components/src/components/expandable-layout/expandable-layout.ts
  src/storybook/src/modul-components/components/expandable-layout/__snapshots__/expandable-layout.stories.ts.snap
  src/storybook/src/modul-components/components/expandable-layout/expandable-layout.stories.ts
Labels: enhancement

#162 [m-timepicker] added support for required maker for timepicker
  packages/modul-components/src/components/timepicker/timepicker.html
  packages/modul-components/src/components/timepicker/timepicker.sandbox.html
  src/storybook/src/modul-components/components/form/__snapshots__/form.all-fields.stories.ts.snap
  src/storybook/src/modul-components/components/timepicker/__snapshots__/timepicker.stories.ts.snap
  src/storybook/src/modul-components/components/timepicker/timepicker.stories.ts
Labels: enhancement

#166 [m-rich-text-editor] Remove rte-*.scss from commons
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.scss
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.ts
  packages/modul-components/src/components/rich-text-editor/rte-internal.scss
  packages/modul-components/src/components/rich-text-editor/rte-theme.scss
  packages/modul-components/src/components/rich-text/rich-text.scss
  packages/modul-components/src/styles/mixins/_mixins.scss
Labels: bug fix

#168 [drag-and-drop] Remove drag and drop scss from commons
  packages/modul-components/src/directives/drag-and-drop/drag-and-drop-plugin.ts
  packages/modul-components/src/directives/drag-and-drop/drag-and-drop.scss
Labels: bug fix

#174 [$http] Feature/ael 1999
  .gitignore
  packages/modul-components/src/utils/http/http.ts
Labels: bug fix

#180 bugfix/phonenumber-prefixes => phonefield prefixes correction
  packages/modul-components/src/components/phonefield/assets/all-countries-en.ts
  packages/modul-components/src/components/phonefield/assets/all-countries-fr.ts
Labels: bug fix

#172 [m-expandable-layout] Ajouter z-index sur le panneau en mode overContent
  packages/modul-components/src/components/expandable-layout/expandable-layout.scss
  src/storybook/src/modul-components/components/expandable-layout/__snapshots__/expandable-layout.stories.ts.snap
  src/storybook/src/modul-components/components/expandable-layout/expandable-layout.stories.ts
Labels: enhancement

#177 [drag-and-drop] Feature/ena2 8587 drag clean up
  packages/modul-components/src/directives/drag-and-drop/drag-and-drop-plugin.ts
  packages/modul-components/src/directives/drag-and-drop/drag-and-drop.sandbox.html
  packages/modul-components/src/directives/drag-and-drop/drag-and-drop.sandbox.ts
  packages/modul-components/src/directives/drag-and-drop/drag-and-drop.scss
  src/storybook/src/modul-components/components/drag-and-drop/sortable-sandbox.scss
Labels: bug fix

#173 [m-address] MODUL-1209 - Add error message on address-lookup-field
  packages/modul-components/src/components/address/address-lookup-field/address-lookup-field.html
  packages/modul-components/src/components/address/address-lookup-field/address-lookup-field.ts
Labels: enhancement
