Repository ulaval/modul, pull requests merged in 2019-11, with the labels that each got.

#117 RichTextEditor: Ajustement visuel
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.scss
Labels: bug fix

#119 Feature/ael 1517 - implementation virtual-scroll dans le m-select
  packages/modul-components/package.json
  packages/modul-components/src/components/phonefield/phonefield.html
  packages/modul-components/src/components/phonefield/phonefield.scss
  packages/modul-components/src/components/select/base-select/base-select.html
  packages/modul-components/src/components/select/base-select/base-select.scss
  packages/modul-components/src/components/select/base-select/base-select.ts
  packages/modul-components/src/components/select/select.html
  packages/modul-components/src/components/select/select.ts
  src/storybook/conf/storybook/config.ts
  src/storybook/src/modul-components/components/select/__snapshots__/select.stories.ts.snap
  src/storybook/src/modul-components/components/select/select.stories.ts
  yarn.lock
Labels: bug fix, enhancement

#121 use cursor pointer by default on mlink
  packages/modul-components/src/components/link/link.scss
Labels: bug fix

#124 bugfix/m_rich_text_editor_problem_with_click_on_options
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.html
  packages/modul-components/src/components/rich-text-editor/rich-text-editor.html
Labels: bug fix

#122 bugfix / Optimize chunking for phonefield + visual bug
  packages/modul-components/src/components/phonefield/phonefield.html
  packages/modul-components/src/components/phonefield/phonefield.scss
  packages/modul-components/src/components/phonefield/phonefield.ts
  packages/modul-components/src/components/rich-text-editor/rich-text-editor.ts
  packages/modul-components/src/components/select/select.ts
  packages/modul-components/src/utils/svg/sprites.ts
  src/storybook/src/modul-components/components/phonefield/__snapshots__/phonefield.stories.ts.snap
  src/storybook/src/modul-components/components/phonefield/phonefield.stories.ts
  src/storybook/src/modul-components/components/rich-text-editor/rich-text-editor.sandbox.ts
  src/storybook/tsconfig.json
Labels: breaking change, bug fix

#123 feature/form builder
  packages/modul-components/src/utils/form/builder/form-builder-test-classes.ts
  packages/modul-components/src/utils/form/builder/form-builder.spec.ts
  packages/modul-components/src/utils/form/builder/form-builder.ts
Labels: enhancement

#137 MDropdown - Mobile - Disabled
  packages/modul-components/src/mixins/portal/portal.ts
Labels: bug fix

#54 Feature/ena2 7833 m photo editor
  packages/modul-components/package.json
  packages/modul-components/src/components/component-names.ts
  packages/modul-components/src/components/file-select/file-select.spec.ts
  packages/modul-components/src/components/file-select/file-select.ts
  packages/modul-components/src/components/photo-editor/__snapshots__/photo-editor.spec.ts.snap
  packages/modul-components/src/components/photo-editor/component-names.ts
  packages/modul-components/src/components/photo-editor/crop-image/crop-image.html
  packages/modul-components/src/components/photo-editor/crop-image/crop-image.scss
  packages/modul-components/src/components/photo-editor/crop-image/crop-image.spec.ts
  packages/modul-components/src/components/photo-editor/crop-image/crop-image.ts
  packages/modul-components/src/components/photo-editor/image-displayer/image-displayer.html
  packages/modul-components/src/components/photo-editor/image-displayer/image-displayer.scss
  packages/modul-components/src/components/photo-editor/image-displayer/image-displayer.spec.ts
  packages/modul-components/src/components/photo-editor/image-displayer/image-displayer.ts
  packages/modul-components/src/components/photo-editor/photo-editor.html
  packages/modul-components/src/components/photo-editor/photo-editor.lang.en.json
  packages/modul-components/src/components/photo-editor/photo-editor.lang.fr.json
  packages/modul-components/src/components/photo-editor/photo-editor.scss
  packages/modul-components/src/components/photo-editor/photo-editor.spec.ts
  packages/modul-components/src/components/photo-editor/photo-editor.ts
  packages/modul-components/src/lang/en.ts
  packages/modul-components/src/lang/fr.ts
  packages/modul-components/src/utils/file/file.spec.ts
  packages/modul-components/src/utils/file/file.ts
  src/storybook/src/modul-components/components/photo-editor/__snapshots__/crop-image.stories.ts.snap
  src/storybook/src/modul-components/components/photo-editor/__snapshots__/photo-editor.stories.ts.snap
  src/storybook/src/modul-components/components/photo-editor/photo-editor.stories.ts
  yarn.lock
Labels: new feature

#129 Status text: display items number instead of pages
  packages/modul-components/src/components/pagination/pagination.lang.en.json
  packages/modul-components/src/components/pagination/pagination.lang.fr.json
  packages/modul-components/src/components/pagination/pagination.ts
  src/storybook/src/modul-components/components/pagination/__snapshots__/pagination.stories.ts.snap
  src/storybook/src/modul-components/components/pagination/pagination.stories.ts
Labels: enhancement

#130 MODUL-1204 - Use Promise instead of url on proxy google
  packages/modul-components/src/components/address/address.ts
  packages/modul-components/src/utils/address-lookup/address-lookup-proxy-google-service.ts
  packages/modul-components/src/utils/address-lookup/address-lookup-proxy-google.ts
  packages/modul-components/src/utils/address-lookup/address-lookup-response-mapper.ts
  packages/modul-components/src/utils/address-lookup/address-lookup.plugin.ts
Labels: breaking change, enhancement

#134 ENA2-8551 - ajout retrait srcset sur les images dans froala
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.ts
Labels: bug fix

#135 bugfix/m-dropdown-focus-mobile => disable dropdown input focus
  packages/modul-components/src/components/dropdown/dropdown.ts
  src/storybook/src/modul-components/components/dropdown/__snapshots__/dropdown.stories.ts.snap
  src/storybook/src/modul-components/components/dropdown/dropdown.stories.ts
Labels: bug fix

#133 Supprimer le border-top sur le projet accodéon
  packages/modul-components/src/components/accordion/accordion.scss
Labels: bug fix

#118 M-form: prendre en compte les erreurs de cohérence dans le compte d'erreur du toast
  packages/modul-components/src/components/form/form.lang.fr.json
  packages/modul-components/src/components/form/form.ts
  src/storybook/src/modul-components/components/form/__snapshots__/form.stories.ts.snap
  src/storybook/src/modul-components/components/form/form.rules.stories.ts
  src/storybook/src/modul-components/components/form/form.stories.ts
  src/storybook/src/modul-components/components/form/sandboxes/form-complex.sandbox.html
Labels: bug fix

#127 Feature/ena2 8504 Focus perdu radio
  packages/modul-components/src/components/radio/radio.html
  packages/modul-components/src/components/radio/radio.scss
  packages/modul-components/src/components/radio/radio.ts
  src/storybook/src/modul-components/components/radio-group/__snapshots__/radio-group.stories.ts.snap
  src/storybook/src/modul-components/components/radio/__snapshots__/radio.stories.ts.snap
Labels: bug fix

#141 bugfix / Dropdown gestion du focus champs recherche en mode mobile
  packages/modul-components/src/components/dropdown/dropdown.html
  packages/modul-components/src/components/dropdown/dropdown.ts
  src/storybook/src/modul-components/components/autocomplete/__snapshots__/autocomplete.sandbox.stories.ts.snap
  src/storybook/src/modul-components/components/autocomplete/autocomplete.sandbox.html
  src/storybook/src/modul-components/components/autocomplete/autocomplete.sandbox.stories.ts
  src/storybook/src/modul-components/components/autocomplete/autocomplete.sandbox.ts
  src/storybook/src/modul-components/components/dropdown/__snapshots__/dropdown.sandbox.stories.ts.snap
  src/storybook/src/modul-components/components/dropdown/__snapshots__/dropdown.stories.ts.snap
  src/storybook/src/modul-components/components/dropdown/dropdown.sandbox.html
  src/storybook/src/modul-components/components/dropdown/dropdown.sandbox.stories.ts
  src/storybook/src/modul-components/components/dropdown/dropdown.sandbox.ts
  src/storybook/src/modul-components/components/dropdown/dropdown.stories.ts
  src/storybook/src/modul-components/components/form/__snapshots__/form.all-fields.stories.ts.snap
Labels: bug fix

#142 Feature/ena2 8006 alignement image rte
  packages/modul-components/src/components/rich-text-editor/adapter/image-layout-commands.ts
  packages/modul-components/src/styles/mixins/_rte-internal.scss
Labels: bug fix

#143 bugfix/fix googlemap type exports
  packages/modul-components/src/utils/address-lookup/address-lookup-proxy-google-service.ts
  packages/modul-components/src/utils/address-lookup/address-lookup-proxy-google.ts
Labels: bug fix

#144 change dropdown item disabled color
  packages/modul-components/src/components/dropdown/dropdown-item/dropdown-item.scss
  src/storybook/src/modul-components/components/dropdown/__snapshots__/dropdown.stories.ts.snap
  src/storybook/src/modul-components/components/dropdown/dropdown.stories.ts
Labels: bug fix

#147 Disable datepicker input-mask focus on mobile
  packages/modul-components/src/components/datepicker/datepicker.html
  packages/modul-components/src/components/datepicker/datepicker.ts
Labels: bug fix

#146 Performance issue: refactoring calendar-button to a Render Functions
  CODEOWNERS
  packages/modul-components/src/components/calendar/calendar-button/calendar-button.html
  packages/modul-components/src/components/calendar/calendar-button/calendar-button.ts
  packages/modul-components/src/components/calendar/calendar-renderer/base-calendar/__snapshots__/base-calendar.spec.ts.snap
  packages/modul-components/src/components/calendar/calendar-renderer/base-calendar/base-calendar.html
  packages/modul-components/src/components/calendar/calendar-renderer/base-calendar/base-calendar.ts
  packages/modul-components/src/components/timepicker/timepicker.html
  packages/modul-components/src/components/timepicker/timepicker.ts
Labels: bug fix

#47 Permettre d'ajouter des menu-item au menu-item dynamiquement
  packages/modul-components/src/components/inplace-edit/inplace-edit.html
  packages/modul-components/src/components/menu/menu-item/menu-item.html
  packages/modul-components/src/components/menu/menu-item/menu-item.ts
  packages/modul-components/src/components/menu/menu.html
  packages/modul-components/src/components/menu/menu.ts
  src/storybook/src/modul-components/components/menu/__snapshots__/menu.stories.ts.snap
  src/storybook/src/modul-components/components/menu/menu.stories.ts
Labels: enhancement

#69 Ajouter des emits dans le inplace-edit
  packages/modul-components/src/components/inplace-edit/inplace-edit.html
  packages/modul-components/src/components/inplace-edit/inplace-edit.spec.ts
  packages/modul-components/src/components/inplace-edit/inplace-edit.ts
  packages/modul-components/src/components/overlay/overlay.html
  packages/modul-components/src/components/overlay/overlay.ts
Labels: enhancement

#128 Feature/ena2 8119 rte copier coller
  packages/modul-components/src/components/rich-text-editor/rich-text-editor-options.ts
Labels: bug fix

#132 Add max-width prop for m-option
  packages/modul-components/src/components/option/option-item/option-item.scss
  packages/modul-components/src/components/option/option.html
  packages/modul-components/src/components/option/option.ts
  src/storybook/src/modul-components/components/option/__snapshots__/option.stories.ts.snap
  src/storybook/src/modul-components/components/option/option.stories.ts
Labels: enhancement

#152 MToast optional close button
  packages/modul-components/src/components/toast/toast.html
  packages/modul-components/src/components/toast/toast.ts
  packages/modul-components/src/utils/toast/toast-service.ts
  src/storybook/src/modul-components/components/toast/__snapshots__/toast.stories.ts.snap
  src/storybook/src/modul-components/components/toast/toast.stories.ts
Labels: enhancement

#154 Bugfix/navbar item resizing optimization
  packages/modul-components/src/components/navbar/navbar-item/navbar-item.ts
Labels: bug fix, do not merge, visual breaking change
