Repository ulaval/modul, pull requests merged in 2019-09, with the labels that each got.

#24 bugfix/autocomplete_duplicated_keys => index des items
  packages/modul-components/src/components/autocomplete/autocomplete.html
Labels: bug fix

#27 Feature/phonefield detect country
  packages/modul-components/src/components/phonefield/__snapshots__/phonefield.stories.ts.snap
  packages/modul-components/src/components/phonefield/phonefield.stories.ts
  packages/modul-components/src/components/phonefield/phonefield.ts
Labels: enhancement

#13 MODUL-1186: Nouveau composant typeahead
  packages/modul-components/src/components/autocomplete/autocomplete.html
  packages/modul-components/src/components/component-names.ts
  packages/modul-components/src/components/components-plugin.ts
  packages/modul-components/src/components/dropdown/dropdown.html
  packages/modul-components/src/components/dropdown/dropdown.ts
  packages/modul-components/src/components/phonefield/__snapshots__/phonefield.stories.ts.snap
  packages/modul-components/src/components/phonefield/phonefield.html
  packages/modul-components/src/components/phonefield/phonefield.ts
  packages/modul-components/src/components/popup/popup.html
  packages/modul-components/src/components/popup/popup.ts
  packages/modul-components/src/components/select/__snapshots__/select.stories.ts.snap
  packages/modul-components/src/components/select/base-select/base-select.html
  packages/modul-components/src/components/select/base-select/base-select.scss
  packages/modul-components/src/components/select/base-select/base-select.ts
  packages/modul-components/src/components/select/select-item/select-item.html
  packages/modul-components/src/components/select/select-item/select-item.scss
  packages/modul-components/src/components/select/select-item/select-item.ts
  packages/modul-components/src/components/select/select.html
  packages/modul-components/src/components/select/select.scss
  packages/modul-components/src/components/select/select.stories.ts
  packages/modul-components/src/components/select/select.ts
  packages/modul-components/src/components/sidebar/sidebar.html
  packages/modul-components/src/components/sidebar/sidebar.sandbox.html
  packages/modul-components/src/components/sidebar/sidebar.scss
  packages/modul-components/src/components/sidebar/sidebar.ts
  packages/modul-components/src/components/typeahead/__snapshots__/typeahead.stories.ts.snap
  packages/modul-components/src/components/typeahead/typeahead.html
  packages/modul-components/src/components/typeahead/typeahead.lang.en.json
  packages/modul-components/src/components/typeahead/typeahead.lang.fr.json
  packages/modul-components/src/components/typeahead/typeahead.scss
  packages/modul-components/src/components/typeahead/typeahead.stories.ts
  packages/modul-components/src/components/typeahead/typeahead.ts
  packages/modul-components/src/lang/en.ts
  packages/modul-components/src/lang/fr.ts
  packages/modul-components/src/mixins/input-popup/input-popup.ts
Labels: new feature, visual breaking change

#38 Améliorer la réactivité d'affichage des $slots du composant m-panel
  packages/modul-components/src/components/panel/__snapshots__/panel.spec.ts.snap
  packages/modul-components/src/components/panel/__snapshots__/panel.stories.ts.snap
  packages/modul-components/src/components/panel/panel.html
  packages/modul-components/src/components/panel/panel.sandbox.html
  packages/modul-components/src/components/panel/panel.sandbox.ts
  packages/modul-components/src/components/panel/panel.scss
  packages/modul-components/src/components/panel/panel.spec.ts
  packages/modul-components/src/components/panel/panel.stories.ts
  packages/modul-components/src/components/panel/panel.ts
Labels: bug fix

#42 Feature/ena2 7657 external sprites
  packages/modul-components/src/assets/icons/sprites-default.svg
  packages/modul-components/src/assets/icons/sprites-flags.svg
  packages/modul-components/src/components/icon/icon.ts
  packages/modul-components/src/components/phonefield/phonefield.ts
  packages/modul-components/src/utils/svg/default-sprites.ts
  packages/modul-components/src/utils/svg/sprites.ts
  src/modul-website/src/utils/svg.ts
Labels: enhancement

#57 Correction dropdown qui ouvre lors d'un choix dans la liste déroulante
  packages/modul-components/src/components/popup/popup.ts
Labels: bug fix

#52 Correction du compte d'erreur dans le toast du mForm
  packages/modul-components/src/components/form/__snapshots__/form.stories.ts.snap
  packages/modul-components/src/components/form/form.stories.ts
  packages/modul-components/src/components/form/form.ts
Labels: bug fix

#56 Correctifs validateurs m-form + modification validation de groupe au submit
  packages/modul-components/src/components/form/__snapshots__/form.stories.ts.snap
  packages/modul-components/src/components/form/form.html
  packages/modul-components/src/components/form/form.stories.ts
  packages/modul-components/src/components/form/form.ts
  packages/modul-components/src/utils/form/abstract-control.ts
  packages/modul-components/src/utils/form/form-array.ts
  packages/modul-components/src/utils/form/form-control.ts
  packages/modul-components/src/utils/form/form-group.ts
  packages/modul-components/src/utils/form/validators/compare/compare.spec.ts
  packages/modul-components/src/utils/form/validators/compare/compare.ts
  packages/modul-components/src/utils/form/validators/min-length/min-length.ts
Labels: breaking change, bug fix

#62 Tout ouvrir / tout fermer n'affiche pas toujours
  packages/modul-components/src/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
  packages/modul-components/src/components/accordion-group/accordion-group.stories.ts
  packages/modul-components/src/components/accordion-group/accordion-group.ts
Labels: bug fix

#46 Feature/modul 771 multiselect
  packages/modul-components/src/components/chip/__snapshots__/chip.spec.ts.snap
  packages/modul-components/src/components/chip/__snapshots__/chip.stories.ts.snap
  packages/modul-components/src/components/chip/_chip-commons.scss
  packages/modul-components/src/components/chip/chip-add/__snapshots__/chip-add.spec.ts.snap
  packages/modul-components/src/components/chip/chip-add/__snapshots__/chip-add.stories.ts.snap
  packages/modul-components/src/components/chip/chip-add/chip-add.html
  packages/modul-components/src/components/chip/chip-add/chip-add.scss
  packages/modul-components/src/components/chip/chip-add/chip-add.spec.ts
  packages/modul-components/src/components/chip/chip-add/chip-add.stories.ts
  packages/modul-components/src/components/chip/chip-add/chip-add.ts
  packages/modul-components/src/components/chip/chip-delete/__snapshots__/chip-delete.stories.ts.snap
  packages/modul-components/src/components/chip/chip-delete/chip-delete.html
  packages/modul-components/src/components/chip/chip-delete/chip-delete.scss
  packages/modul-components/src/components/chip/chip-delete/chip-delete.stories.ts
  packages/modul-components/src/components/chip/chip-delete/chip-delete.ts
  packages/modul-components/src/components/chip/chip.html
  packages/modul-components/src/components/chip/chip.stories.ts
  packages/modul-components/src/components/chip/chip.ts
  packages/modul-components/src/components/component-names.ts
  packages/modul-components/src/components/icon/icon.html
  packages/modul-components/src/components/icon/icon.ts
  packages/modul-components/src/components/multi-select/__snapshots__/multi-select.stories.ts.snap
  packages/modul-components/src/components/multi-select/multi-select.api.fr.json
  packages/modul-components/src/components/multi-select/multi-select.html
  packages/modul-components/src/components/multi-select/multi-select.lang.en.json
  packages/modul-components/src/components/multi-select/multi-select.lang.fr.json
  packages/modul-components/src/components/multi-select/multi-select.scss
  packages/modul-components/src/components/multi-select/multi-select.stories.ts
  packages/modul-components/src/components/multi-select/multi-select.ts
  packages/modul-components/src/components/phonefield/__snapshots__/phonefield.stories.ts.snap
  packages/modul-components/src/components/popup/popup.ts
  packages/modul-components/src/components/select/__snapshots__/select.stories.ts.snap
  packages/modul-components/src/components/select/base-select/base-select.html
  packages/modul-components/src/components/select/base-select/base-select.scss
  packages/modul-components/src/components/select/base-select/base-select.ts
  packages/modul-components/src/components/select/select-item/select-item.html
  packages/modul-components/src/components/select/select-item/select-item.scss
  packages/modul-components/src/components/select/select-item/select-item.ts
  packages/modul-components/src/components/typeahead/__snapshots__/typeahead.stories.ts.snap
  packages/modul-components/src/components/typeahead/typeahead.ts
  packages/modul-components/src/lang/en.ts
  packages/modul-components/src/lang/fr.ts
  src/modul-website/public/content/components/multi-select/multi-select.meta.fr.json
  src/modul-website/public/content/components/multi-select/multi-select.preview.fr.md
  src/modul-website/src/component-examples/component-example-plugins.ts
  src/modul-website/src/component-examples/multi-select/multi-select.example.html
  src/modul-website/src/component-examples/multi-select/multi-select.example.ts
  src/modul-website/src/modul.ts
Labels: new feature, visual breaking change
