Repository ulaval/modul, pull requests merged in 2020-01, with the labels that each got.

#186 misc/add import helpers to improve bundle size
  packages/modul-components/package.json
  packages/modul-components/tsconfig.lib.json
  src/storybook/tsconfig.json
  yarn.lock
Labels: breaking change, enhancement

#169 [m-timepicker] Pemettre d'ignorer les validations internes du timepicker
  packages/modul-components/src/components/timepicker/timepicker.ts
  src/storybook/src/modul-components/components/timepicker/__snapshots__/timepicker.stories.ts.snap
  src/storybook/src/modul-components/components/timepicker/timepicker.stories.ts
Labels: enhancement

#187 [m-steppers] Ajouter du padding autour de l'icon dans le m-stepper-item
  packages/modul-components/src/components/steppers/steppers-item/steppers-item.html
  packages/modul-components/src/components/steppers/steppers-item/steppers-item.scss
  src/storybook/src/modul-components/components/steppers/__snapshots__/steppers.stories.ts.snap
  src/storybook/src/modul-components/components/steppers/steppers.stories.ts
Labels: visual breaking change

#179 [m-rich-text-editor] ENA2-8976 - Ajout attribut sizes sur les images
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.ts
Labels: enhancement

#189 Bugfix/bump typescriopt to version 3 6 x
  .vscode/settings.json
  package.json
  packages/modul-components/src/components/transitions/accordion-transition/accordion-transition.ts
  packages/modul-components/src/directives/textarea-auto-height/textarea-auto-height.ts
  yarn.lock
Labels: bug fix

#188 [m-rich-text-editor] Keep images size in px after resizing
  packages/modul-components/src/components/rich-text-editor/rich-text-editor-options.ts
Labels: bug fix

#194 [m-file-upload] AEL-2074 ajoute une slot header dans le file-upload
  packages/modul-components/src/components/file-upload/__snapshots__/file-upload.spec.ts.snap
  packages/modul-components/src/components/file-upload/file-upload.html
  packages/modul-components/src/components/file-upload/file-upload.sandbox.html
  packages/modul-components/src/components/file-upload/file-upload.sandbox.ts
  packages/modul-components/src/components/file-upload/file-upload.spec.ts
  src/storybook/src/modul-components/components/file-upload/__snapshots__/file-upload.stories.ts.snap
  src/storybook/src/modul-components/components/file-upload/file-upload.stories.ts
Labels: enhancement

#145 [m-portal] Managed stackId undefined and remove double call to popElement
  packages/modul-components/src/mixins/portal/portal.ts
  packages/modul-components/src/utils/modul/modul.ts
Labels: bug fix

#184 [m-navbar] Bugfix/navbar item resizing optimization
  packages/modul-components/src/components/navbar/navbar-item/__snapshots__/navbar-item.spec.ts.snap
  packages/modul-components/src/components/navbar/navbar-item/navbar-item.html
  packages/modul-components/src/components/navbar/navbar-item/navbar-item.scss
  packages/modul-components/src/components/navbar/navbar-item/navbar-item.spec.ts
  packages/modul-components/src/components/navbar/navbar-item/navbar-item.ts
  src/storybook/src/modul-components/components/navbar/__snapshots__/navbar.stories.ts.snap
  src/storybook/src/modul-components/components/navbar/navbar.sandbox.html
  src/storybook/src/modul-components/components/navbar/navbar.stories.ts
  src/storybook/src/modul-components/components/transitions/slide-transition/__snapshots__/slide-transition.stories.ts.snap
  src/storybook/src/modul-components/components/tree/__snapshots__/autocomplete.sandbox.stories.ts.snap
Labels: bug fix, enhancement

#193 [scss] Refactor pour utiliser en WebComponent et Custom Element
  packages/modul-components/src/components/dialog/dialog.html
  packages/modul-components/src/components/file-upload/__snapshots__/file-upload.spec.ts.snap
  packages/modul-components/src/components/file-upload/file-upload.html
  packages/modul-components/src/components/file-upload/file-upload.scss
  packages/modul-components/src/components/file-upload/file-upload.spec.ts
  packages/modul-components/src/components/pagination/pagination.scss
  packages/modul-components/src/components/progress/progress.scss
  packages/modul-components/src/components/progress/progress.ts
  packages/modul-components/src/components/spinner/spinner.scss
  packages/modul-components/src/components/tree/tree.scss
  packages/modul-components/src/styles/base/_animations.scss
  packages/modul-components/src/styles/base/_base.scss
  packages/modul-components/src/styles/base/_font.scss
  packages/modul-components/src/styles/mixins/_animation.scss
  packages/modul-components/src/styles/mixins/_mixins.scss
  src/storybook/src/modul-components/components/progress/__snapshots__/progress.sandbox.stories.ts.snap
  src/storybook/src/modul-components/components/progress/progress.sandbox.html
  src/storybook/src/modul-components/components/progress/progress.sandbox.stories.ts
  src/storybook/src/modul-components/components/progress/progress.sandbox.ts
Labels: enhancement

#203 [scss] Add missing font import to main.scss
  packages/modul-components/src/styles/font/_font.scss
  packages/modul-components/src/styles/main.scss
Labels: bug fix
