Repository ulaval/modul, pull requests merged in 2020-04, with the labels that each got.

#267 Mixin global pour la configuration individuelle des composantes MODUL
  packages/modul-components/src/components/phonefield/phonefield.ts
  packages/modul-components/src/lang/en.ts
  packages/modul-components/src/lang/fr.ts
  packages/modul-components/src/lib.ts
  packages/modul-components/src/utils/component/component-mixin.ts
  packages/modul-components/src/utils/utils-plugin.ts
Labels: enhancement, next

#278 Bugfix/correctif pour le phonefield
  packages/modul-components/src/components/phonefield/phonefield.html
Labels: bug fix

#269 [m-expandable-layout] Set height 100% on panel content
  packages/modul-components/src/components/expandable-layout/expandable-layout.scss
Labels: bug fix

#271 [M-ORGANIZE-TABLE-COLUMNS-MODAL] Ajout d'une slot pour un bouton trigger custom
  packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns-modal.html
  src/storybook/src/modul-components/components/organize-table-columns-modal/__snapshots__/organize-table-columns-modal.stories.ts.snap
  src/storybook/src/modul-components/components/organize-table-columns-modal/organize-table-columns-modal.stories.ts
Labels: enhancement

#273 [m-overlay] Ajout d'une props pour enlever le footer
  packages/modul-components/src/components/overlay/overlay.html
  packages/modul-components/src/components/overlay/overlay.ts
  src/storybook/src/modul-components/components/overlay/__snapshots__/overlay.stories.ts.snap
  src/storybook/src/modul-components/components/overlay/overlay.stories.ts
Labels: enhancement

#276 fix security issues
  yarn.lock
Labels: bug fix

#277 [f-m-time-elapsed] - Création du filtre temps écoulés
  packages/modul-components/src/filters/date/date.ts
  packages/modul-components/src/filters/date/time-elapsed/time-elapsed.lang.en.json
  packages/modul-components/src/filters/date/time-elapsed/time-elapsed.lang.fr.json
  packages/modul-components/src/filters/date/time-elapsed/time-elapsed.ts
  packages/modul-components/src/filters/filter-names.ts
  packages/modul-components/src/lang/en.ts
  packages/modul-components/src/lang/fr.ts
  src/storybook/src/modul-components/filters/date/time-elapsed/__snapshots__/time-elapsed.stories.ts.snap
  src/storybook/src/modul-components/filters/date/time-elapsed/time-elapsed.stories.ts
  src/storybook/tests/polyfills.js
Labels: new feature

#274 [$i18n] Added support for the 0 quantifier for translation keys
  packages/modul-components/src/utils/i18n/i18n.spec.lang.fr.json
  packages/modul-components/src/utils/i18n/i18n.spec.ts
  packages/modul-components/src/utils/i18n/i18n.ts
Labels: enhancement

#280 Feature/enhancenment component options
  packages/modul-components/src/utils/component/component-mixin.ts
  src/storybook/src/modul-components/components/phonefield/__snapshots__/phonefield.stories.ts.snap
Labels: enhancement, next

#283 m-phonefield: Fixer la largeur du dropdown du drapeau
  packages/modul-components/src/components/phonefield/phonefield.scss
Labels: bug fix, enhancement

#282 [f-m-phone] Ajout d'un filtre pour les no de téléphone
  packages/modul-components/src/filters/filter-names.ts
  packages/modul-components/src/filters/phone/phone.ts
  src/storybook/src/modul-components/filters/date/time-elapsed/__snapshots__/time-elapsed.stories.ts.snap
  src/storybook/src/modul-components/filters/date/time-elapsed/time-elapsed.stories.ts
  src/storybook/src/modul-components/filters/phone/__snapshots__/phone.stories.ts.snap
  src/storybook/src/modul-components/filters/phone/phone.stories.ts
Labels: new feature

#285 ModulDate: Addition et soustraction des dates par mois ou par jour
  packages/modul-components/src/components/datepicker/datepicker.ts
  packages/modul-components/src/utils/modul-date/modul-date.spec.ts
  packages/modul-components/src/utils/modul-date/modul-date.ts
Labels: enhancement, new feature

#286 m-table: ajuster la largeur du placeholder du tableau
  packages/modul-components/src/components/table/__snapshots__/table.spec.ts.snap
  packages/modul-components/src/components/table/table.html
  packages/modul-components/src/components/table/table.scss
  src/storybook/src/modul-components/components/table/__snapshots__/table.stories.ts.snap
Labels: bug fix

#288 [m-radio-group] Ajout de la props validationMessagePosition
  packages/modul-components/src/components/radio-group/radio-group.html
  packages/modul-components/src/components/radio-group/radio-group.ts
  src/storybook/src/modul-components/components/radio-group/__snapshots__/radio-group.stories.ts.snap
  src/storybook/src/modul-components/components/radio-group/radio-group.stories.ts
Labels: enhancement

#291 [m-phonefield] - Fix du model non cohérent dans Brio VS Modul
  packages/modul-components/src/components/phonefield/phonefield.html
  packages/modul-components/src/components/phonefield/phonefield.ts
Labels: bug fix

#290 [m-form] Ajout de méthodes dans le form-group et modification de removeControl
  packages/modul-components/src/utils/form/form-group.spec.ts
  packages/modul-components/src/utils/form/form-group.ts
Labels: enhancement

#294 [m-phonefield] Remove cleave-phone.i18n.js
  packages/modul-components/src/components/input-mask/input-mask.html
  packages/modul-components/src/components/input-mask/input-mask.ts
  packages/modul-components/src/components/phonefield/formatter/custom-asyoutype.ts
  packages/modul-components/src/components/phonefield/phonefield.html
  packages/modul-components/src/components/phonefield/phonefield.scss
  packages/modul-components/src/components/phonefield/phonefield.ts
  src/storybook/src/modul-components/components/phonefield/__snapshots__/phonefield.stories.ts.snap
  src/storybook/src/modul-components/components/phonefield/phonefield.stories.ts
Labels: enhancement

#295 [m-integerfield] - Ajout autocomplete au m-integerfield + stories
  packages/modul-components/src/components/integerfield/integerfield.html
  src/storybook/src/modul-components/components/integerfield/__snapshots__/integerfield.stories.ts.snap
  src/storybook/src/modul-components/components/integerfield/integerfield.stories.ts
Labels: enhancement

#296 [ControlValidator] - Ajouter le PhoneValidator pour la validation dans le m-form
  packages/modul-components/src/components/form/form.lang.en.json
  packages/modul-components/src/components/form/form.lang.fr.json
  packages/modul-components/src/utils/form/validators/phone/phone.spec.ts
  packages/modul-components/src/utils/form/validators/phone/phone.ts
  packages/modul-components/src/utils/form/validators/validator-error-keys.ts
  src/storybook/src/modul-components/components/form/__snapshots__/form.validators.stories.ts.snap
  src/storybook/src/modul-components/components/form/form.validators.stories.ts
Labels: enhancement
