Repository ulaval/modul, pull requests merged in 2020-07, with the labels that each got.

#363 MMultiSelect - Correction d'affichage lorsque la liste est vide
  packages/modul-components/src/components/multi-select/multi-select.ts
  src/storybook/src/modul-components/components/multi-select/__snapshots__/multi-select.stories.ts.snap
  src/storybook/src/modul-components/components/multi-select/multi-select.stories.ts
Labels: bug fix, visual breaking change

#362 MSearchfield - Alignement de l'icône de recherche
  packages/modul-components/src/components/searchfield/searchfield.html
  packages/modul-components/src/components/searchfield/searchfield.scss
  src/storybook/src/modul-components/components/searchfield/__snapshots__/searchfield.stories.ts.snap
Labels: bug fix

#366 Modification du titre du photo editor
  packages/modul-components/src/components/photo-editor/photo-editor.lang.en.json
  packages/modul-components/src/components/photo-editor/photo-editor.lang.fr.json
Labels: enhancement

#359 Feature - Add icon help-circle
  packages/modul-components/src/assets/icons/sprites-default.svg
  packages/modul-components/src/assets/icons/svg/help-circle.svg
  packages/modul-components/src/utils/modul-icons/modul-icons.ts
  src/storybook/src/modul-components/components/svg/__snapshots__/svg-categories.stories.ts.snap
  src/storybook/src/modul-components/components/svg/svg-categories.stories.ts
  src/storybook/src/modul-components/components/svg/svg-importation.ts
Labels: new feature, next

#347 [m-option] Nettoyer le code + importer les composants dans le @Component
  packages/modul-components/src/components/option/option-item/option-item-predefined.html
  packages/modul-components/src/components/option/option-item/option-item-predefined.ts
  packages/modul-components/src/components/option/option-item/option-item.html
  packages/modul-components/src/components/option/option-item/option-item.ts
  packages/modul-components/src/components/option/option-title/option-title.html
  packages/modul-components/src/components/option/option.html
Labels: next

#348 [m-organize-table-columns] Nettoyage du HTML + Modifier importation de composants
  packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns-modal.ts
  packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns/organize-table-columns.html
  packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns/organize-table-columns.ts
Labels: next

#360 Feature/new component: auto-horizontal-scroll
  packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.api.fr.json
  packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.html
  packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.lang.en.json
  packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.lang.fr.json
  packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.scss
  packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.ts
  packages/modul-components/src/components/component-names.ts
  packages/modul-components/src/components/components-plugin.ts
  src/modul-website/public/content/components/auto-horizontal-scroll/auto-horizontal-scroll.meta.fr.json
  src/modul-website/public/content/components/auto-horizontal-scroll/auto-horizontal-scroll.preview.fr.md
  src/modul-website/src/components/expendable-panel/expandable-panel.scss
  src/storybook/src/modul-components/components/auto-horizontal-scroll/__snapshots__/auto-horizontal-scroll-carousel.stories.ts.snap
  src/storybook/src/modul-components/components/auto-horizontal-scroll/__snapshots__/auto-horizontal-scroll-gradient-skin.stories.ts.snap
  src/storybook/src/modul-components/components/auto-horizontal-scroll/__snapshots__/auto-horizontal-scroll.stories.ts.snap
  src/storybook/src/modul-components/components/auto-horizontal-scroll/auto-horizontal-scroll-carousel.stories.ts
  src/storybook/src/modul-components/components/auto-horizontal-scroll/auto-horizontal-scroll-gradient-skin.stories.ts
  src/storybook/src/modul-components/components/auto-horizontal-scroll/auto-horizontal-scroll.stories.ts
  src/storybook/src/modul.ts
Labels: new feature, next

#361 Feature/new component: m-empty-area
  packages/modul-components/src/components/component-names.ts
  packages/modul-components/src/components/components-plugin.ts
  packages/modul-components/src/components/empty-area/empty-area.api.fr.json
  packages/modul-components/src/components/empty-area/empty-area.html
  packages/modul-components/src/components/empty-area/empty-area.scss
  packages/modul-components/src/components/empty-area/empty-area.ts
  src/modul-website/public/content/components/avatar/avatar.meta.fr.json
  src/modul-website/public/content/components/chip/chip.meta.fr.json
  src/modul-website/public/content/components/decimalfield/decimalfield.meta.fr.json
  src/modul-website/public/content/components/empty-area/empty-area.meta.fr.json
  src/modul-website/public/content/components/empty-area/empty-area.preview.fr.md
  src/modul-website/public/content/components/error-page/error-page.meta.fr.json
  src/modul-website/public/content/components/expandable-layout/expandable-layout.meta.fr.json
  src/modul-website/public/content/components/integerfield/integerfield.meta.fr.json
  src/modul-website/public/content/components/moneyfield/moneyfield.meta.fr.json
  src/modul-website/public/content/components/organize-table-columns-modal/organize-table-columns-modal.meta.fr.json
  src/modul-website/public/content/components/postalcodefield/postalcodefield.meta.fr.json
  src/storybook/src/modul-components/components/empty-area/__snapshots__/empty-area.stories.ts.snap
  src/storybook/src/modul-components/components/empty-area/empty-area.stories.ts
  src/storybook/src/modul-components/components/svg/svg-importation.ts
  src/storybook/src/modul.ts
Labels: new feature, next

#371 [m-repeater] Fix pour problem dans 1_2
  packages/modul-components/src/components/repeater/repeater.ts
  src/storybook/src/modul-components/components/repeater/__snapshots__/repeater.stories.ts.snap
Labels: bug fix, next

#376 [m-dropdown ]add filter to dropdown
  packages/modul-components/src/components/dropdown/dropdown.ts
Labels: bug fix
