Repository ulaval/modul, pull requests merged in 2020-03, with the labels that each got.

#240 [m-tooltip] add customisable max-height
  packages/modul-components/src/components/tooltip/tooltip.scss
  packages/modul-components/src/components/tooltip/tooltip.ts
Labels: enhancement

#229 MOrganizeTableColumns - New feature
  packages/modul-components/src/components/component-names.ts
  packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns-modal.api.fr.json
  packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns-modal.html
  packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns-modal.lang.en.json
  packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns-modal.lang.fr.json
  packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns-modal.ts
  packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns/organize-table-columns.api.fr.json
  packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns/organize-table-columns.html
  packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns/organize-table-columns.lang.en.json
  packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns/organize-table-columns.lang.fr.json
  packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns/organize-table-columns.scss
  packages/modul-components/src/components/organize-table-columns-modal/organize-table-columns/organize-table-columns.ts
  packages/modul-components/src/components/table/table.ts
  packages/modul-components/src/lang/en.ts
  packages/modul-components/src/lang/fr.ts
  src/modul-website/public/content/components/organize-table-columns-modal/organize-table-columns-modal.meta.fr.json
  src/modul-website/public/content/components/organize-table-columns-modal/organize-table-columns-modal.preview.fr.md
  src/modul-website/src/component-examples/component-example-plugins.ts
  src/modul-website/src/component-examples/organize-table-columns-modal/organize-table-columns-modal.example.html
  src/modul-website/src/component-examples/organize-table-columns-modal/organize-table-columns-modal.example.ts
  src/modul-website/src/modul.ts
  src/storybook/src/modul-components/components/organize-table-columns-modal/__snapshots__/organize-table-columns-modal.stories.ts.snap
  src/storybook/src/modul-components/components/organize-table-columns-modal/organize-table-columns-modal.stories.ts
  src/storybook/src/modul-components/components/organize-table-columns/__snapshots__/organize-table-columns.stories.ts.snap
  src/storybook/src/modul-components/components/organize-table-columns/organize-table-columns.stories.ts
  src/storybook/src/modul-website/website.stories.ts
  src/storybook/src/modul.ts
Labels: new feature, next

#244 [m-maskedfield] - Création du composant pour faire des masques d'input
  packages/modul-components/src/components/component-names.ts
  packages/modul-components/src/components/input-mask/input-mask.ts
  packages/modul-components/src/components/maskedfield/maskedfield.html
  packages/modul-components/src/components/maskedfield/maskedfield.scss
  packages/modul-components/src/components/maskedfield/maskedfield.ts
  src/storybook/src/modul-components/components/maskedfield/__snapshots__/maskedfield.stories.ts.snap
  src/storybook/src/modul-components/components/maskedfield/maskedfield.stories.ts
  src/storybook/src/modul.ts
Labels: enhancement

#248 [m-phonefield] - Ajout d'une props de liste prioritaire de pays
  packages/modul-components/src/components/phonefield/phonefield.html
  packages/modul-components/src/components/phonefield/phonefield.scss
  packages/modul-components/src/components/phonefield/phonefield.ts
  packages/modul-components/src/components/select/base-select/base-select.html
  packages/modul-components/src/components/select/base-select/base-select.ts
  packages/modul-components/src/components/select/select.html
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-opened-ids.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-secondary-content.stories.ts.snap
  src/storybook/src/modul-components/components/button/__snapshots__/button.stories.ts.snap
  src/storybook/src/modul-components/components/drag-and-drop/__snapshots__/sortable.stories.ts.snap
  src/storybook/src/modul-components/components/file-upload/__snapshots__/file-upload.stories.ts.snap
  src/storybook/src/modul-components/components/form/__snapshots__/form.stories.ts.snap
  src/storybook/src/modul-components/components/maskedfield/__snapshots__/maskedfield.stories.ts.snap
  src/storybook/src/modul-components/components/navbar/__snapshots__/navbar.stories.ts.snap
  src/storybook/src/modul-components/components/overlay/__snapshots__/overlay.stories.ts.snap
  src/storybook/src/modul-components/components/phonefield/__snapshots__/phonefield.stories.ts.snap
  src/storybook/src/modul-components/components/phonefield/phonefield.stories.ts
  src/storybook/src/modul-components/components/photo-editor/__snapshots__/photo-editor.stories.ts.snap
  src/storybook/src/modul-components/components/popper/__snapshots__/popper.stories.ts.snap
  src/storybook/src/modul-components/components/radio-group/__snapshots__/radio-group.stories.ts.snap
  src/storybook/src/modul-components/components/searchfield/__snapshots__/searchfield.stories.ts.snap
  src/storybook/src/modul-components/components/select/__snapshots__/select.stories.ts.snap
  src/storybook/src/modul-components/components/select/select.stories.ts
  src/storybook/src/modul-components/components/steppers/__snapshots__/steppers.stories.ts.snap
Labels: enhancement

#253 Ajouter l'icone lock au sprite svg
  packages/modul-components/src/assets/icons/sprites-default.svg
  src/storybook/src/modul-components/components/icon/icon.stories.ts
Labels: enhancement

#246 [m-limit-elements] - Ajout de libellés personnalisés
  packages/modul-components/src/components/limit-elements/limit-elements.ts
  src/storybook/src/modul-components/components/limit-elements/__snapshots__/limit-elements.stories.ts.snap
  src/storybook/src/modul-components/components/limit-elements/limit-elements.stories.ts
Labels: enhancement

#247 [m-postalcodefield] - Création du composant pour les champs code postal
  packages/modul-components/src/components/component-names.ts
  packages/modul-components/src/components/input-mask/input-mask.ts
  packages/modul-components/src/components/postalcodefield/postalcodefield.html
  packages/modul-components/src/components/postalcodefield/postalcodefield.ts
  src/storybook/src/modul-components/components/postalcodefield/__snapshots__/postalcodefield.stories.ts.snap
  src/storybook/src/modul-components/components/postalcodefield/postalcodefield.stories.ts
  src/storybook/src/modul.ts
Labels: new feature

#243 [m-table] Ajouter la prop width-placeholder sur le m-table
  packages/modul-components/src/components/option/option.sandbox.html
  packages/modul-components/src/components/popup/popup.sandbox.html
  packages/modul-components/src/components/table/__snapshots__/table.spec.ts.snap
  packages/modul-components/src/components/table/table.html
  packages/modul-components/src/components/table/table.scss
  packages/modul-components/src/components/table/table.spec.ts
  packages/modul-components/src/components/table/table.ts
  packages/modul-components/src/utils/scroll-to/scroll-to-service.sandbox.html
  src/modul-website/public/content/components/modal/modal.overview.fr.md
  src/modul-website/public/content/components/modal/modal.preview.fr.md
  src/modul-website/public/content/components/overlay/overlay.preview.fr.md
  src/storybook/src/modul-components/components/overlay/__snapshots__/overlay.stories.ts.snap
  src/storybook/src/modul-components/components/overlay/overlay.stories.ts
  src/storybook/src/modul-components/components/popper/__snapshots__/popper.stories.ts.snap
  src/storybook/src/modul-components/components/popper/popper.stories.ts
  src/storybook/src/modul-components/components/table/__snapshots__/table.stories.ts.snap
  src/storybook/src/modul-components/components/table/table.stories.ts
Labels: bug fix, enhancement

#251 [m-modal] [m-overlay] Amélioration de la réactivité des slots et ajustement Padding
  packages/modul-components/src/components/modal/modal.html
  packages/modul-components/src/components/modal/modal.scss
  packages/modul-components/src/components/modal/modal.ts
  packages/modul-components/src/components/overlay/overlay.html
  packages/modul-components/src/components/overlay/overlay.scss
  src/storybook/src/modul-components/components/modal/__snapshots__/modal.stories.ts.snap
  src/storybook/src/modul-components/components/modal/modal.stories.ts
  src/storybook/src/modul-components/components/overlay/__snapshots__/overlay.stories.ts.snap
  src/storybook/src/modul-components/components/overlay/overlay.stories.ts
Labels: bug fix, enhancement

#254 Feature/nouveau composant m-select-virtual-scroll
  packages/modul-components/src/components/component-names.ts
  packages/modul-components/src/components/phonefield/phonefield.html
  packages/modul-components/src/components/phonefield/phonefield.ts
  packages/modul-components/src/components/select-virtual-scroll/select-virtual-scroll.html
  packages/modul-components/src/components/select-virtual-scroll/select-virtual-scroll.scss
  packages/modul-components/src/components/select-virtual-scroll/select-virtual-scroll.ts
  packages/modul-components/src/components/select/base-select/base-select.html
  packages/modul-components/src/components/select/base-select/base-select.ts
  packages/modul-components/src/components/select/select.html
  packages/modul-components/src/components/select/select.ts
  src/storybook/src/modul-components/components/phonefield/__snapshots__/phonefield.stories.ts.snap
  src/storybook/src/modul-components/components/phonefield/phonefield.stories.ts
  src/storybook/src/modul-components/components/select-virtual-scroll/__snapshots__/select-virtual-scroll.stories.ts.snap
  src/storybook/src/modul-components/components/select-virtual-scroll/select-virtual-scroll.stories.ts
  src/storybook/src/modul-components/components/select/__snapshots__/select.stories.ts.snap
  src/storybook/src/modul-components/components/select/select.stories.ts
Labels: enhancement

#262 m-modal et m-dialog: améliorer réactivité des slots
  packages/modul-components/src/components/modal/modal.scss
  packages/modul-components/src/components/modal/modal.ts
Labels: bug fix

#261 m-table: conserver flèche de trie sur cellule personnalisée
  packages/modul-components/src/components/table/__snapshots__/table.spec.ts.snap
  packages/modul-components/src/components/table/table.html
  packages/modul-components/src/components/table/table.scss
  packages/modul-components/src/components/table/table.ts
  src/storybook/src/modul-components/components/table/__snapshots__/table.stories.ts.snap
  src/storybook/src/modul-components/components/table/table.stories.ts
Labels: bug fix

#263 m-modal: Changer condition d'affichage du message d'erreur dans le mounted
  packages/modul-components/src/components/modal/modal.ts
Labels: bug fix

#264 [m-expandable-layout] Remove unwanted scroll when overContent is false
  packages/modul-components/src/components/expandable-layout/expandable-layout.scss
Labels: bug fix

#265 Feature/ena2 7162 modifier ajout suppression form array
  packages/modul-components/src/utils/form/form-array.spec.ts
  packages/modul-components/src/utils/form/form-array.ts
Labels: enhancement
