Repository ulaval/modul, pull requests merged in 2020-09, with the labels that each got.

#394 m-empty-area: Text align with display-mode='inline'
  packages/modul-components/src/components/empty-area/empty-area.scss
  packages/modul-components/src/components/responsive-table/table-group/table-group.scss
Labels: bug fix

#395 m-responsive-table: Personnalisation du spacingTop sur les rows-group
  packages/modul-components/src/components/responsive-table/responsive-table-commons.ts
  packages/modul-components/src/components/responsive-table/responsive-table.html
  packages/modul-components/src/components/responsive-table/responsive-table.scss
  packages/modul-components/src/components/responsive-table/responsive-table.ts
  packages/modul-components/src/components/responsive-table/table-empty-row/table-empty-row.html
  packages/modul-components/src/components/responsive-table/table-group/table-group.scss
  src/storybook/src/modul-components/components/responsive-table/__snapshots__/responsive-table-custom-class-name.stories.ts.snap
  src/storybook/src/modul-components/components/responsive-table/__snapshots__/responsive-table-custom-html.stories.ts.snap
  src/storybook/src/modul-components/components/responsive-table/__snapshots__/responsive-table.stories.ts.snap
  src/storybook/src/modul-components/components/responsive-table/__snapshots__/table-empty-row.stories.ts.snap
  src/storybook/src/modul-components/components/responsive-table/__snapshots__/table-groupe-header-style.stories.ts.snap
  src/storybook/src/modul-components/components/responsive-table/__snapshots__/table-head-style.stories.ts.snap
  src/storybook/src/modul-components/components/responsive-table/__snapshots__/table-rows-style.stories.ts.snap
  src/storybook/src/modul-components/components/responsive-table/group-header-custom-class-name.css
  src/storybook/src/modul-components/components/responsive-table/responsive-table.stories.ts
  src/storybook/src/modul-components/components/responsive-table/table-head-style.stories.ts
Labels: bug fix

#396 Feature/ena2 7453 fleches tri colonne
  packages/modul-components/src/components/table/table.ts
Labels: bug fix

#399 Given m-message-page it's own state ENUM
  packages/modul-components/src/components/message-page/message-page.ts
  packages/modul-components/src/lib.ts
Labels: bug fix

#400 Use default i18n formatting w/multi-select
  packages/modul-components/src/components/multi-select/multi-select.html
  packages/modul-components/src/components/multi-select/multi-select.ts
Labels: bug fix

#402 [m-navbar] Refactoring du composant pour améliorer l'animation, l'usabilité et l'accessibilité
  packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.ts
  packages/modul-components/src/components/navbar/navbar-item/navbar-item.html
  packages/modul-components/src/components/navbar/navbar-item/navbar-item.scss
  packages/modul-components/src/components/navbar/navbar-item/navbar-item.spec.ts
  packages/modul-components/src/components/navbar/navbar-item/navbar-item.ts
  packages/modul-components/src/components/navbar/navbar.html
  packages/modul-components/src/components/navbar/navbar.scss
  packages/modul-components/src/components/navbar/navbar.ts
  src/storybook/src/modul-components/components/navbar/__snapshots__/navbar.stories.ts.snap
  src/storybook/src/modul-components/components/navbar/navbar.stories.ts
  src/storybook/src/modul-components/components/transitions/slide-transition/__snapshots__/slide-transition.stories.ts.snap
Labels: bug fix, enhancement

#406 [scss] - Ajout des vartiable css pour les styles globaux (.m-u--app-body)
  packages/modul-components/src/styles/base/_base.scss
  packages/modul-components/src/styles/mixins/_typography.scss
Labels: enhancement

#407 [m-Navbar] $el undefined dans le navbar
  packages/modul-components/src/components/navbar/navbar.ts
  src/storybook/src/modul-components/components/navbar/__snapshots__/navbar.stories.ts.snap
Labels: bug fix

#408 [m-navbar] Permettre de personnalisé les styles du navbar avec des variables CSS
  packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll-unscoped.scss
  packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.html
  packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.scss
  packages/modul-components/src/components/auto-horizontal-scroll/auto-horizontal-scroll.ts
  packages/modul-components/src/components/navbar/navbar-item/navbar-item.scss
  packages/modul-components/src/components/navbar/navbar-item/navbar-item.ts
  packages/modul-components/src/components/navbar/navbar-unscoped.scss
  packages/modul-components/src/components/navbar/navbar.scss
  packages/modul-components/src/components/navbar/navbar.ts
  src/storybook/src/modul-components/components/navbar/__snapshots__/navbar.stories.ts.snap
  src/storybook/src/modul-components/components/navbar/navbar.stories.ts
Labels: enhancement
