Repository ulaval/modul, pull requests merged in 2020-02, with the labels that each got.

#214 Ajouter le id dans address-lookup
  packages/modul-components/src/utils/address-lookup/address-lookup-loqate-service.spec.ts
  packages/modul-components/src/utils/address-lookup/address-lookup-response-mapper.ts
  packages/modul-components/src/utils/address-lookup/address.ts
Labels: enhancement

#216 [bugfix] Month selection day overflow
  packages/modul-components/src/components/calendar/calendar-state/state/abstract-calendar-state.spec.base.ts
  packages/modul-components/src/components/calendar/calendar-state/state/abstract-calendar-state.ts
Labels: bug fix

#215 Bugfix/ena2 9571 font space
  packages/modul-components/src/assets/fonts/source-sans-variable/SourceSansVariable-Italic.otf.woff
  packages/modul-components/src/assets/fonts/source-sans-variable/SourceSansVariable-Italic.otf.woff2
  packages/modul-components/src/assets/fonts/source-sans-variable/SourceSansVariable-Roman.otf.woff
  packages/modul-components/src/assets/fonts/source-sans-variable/SourceSansVariable-Roman.otf.woff2
  packages/modul-components/src/styles/mixins/_typography.scss
Labels: bug fix

#210 [m-popup] Correctif probleme de resizing pour le popup
  packages/modul-components/src/components/popup/popup.html
  packages/modul-components/src/components/popup/popup.ts
  packages/modul-components/src/mixins/portal/portal.ts
Labels: bug fix

#212 ModulDate toString uses yyyy-mm-dd format
  packages/modul-components/src/utils/modul-date/modul-date.ts
Labels: bug fix

#204 Rich Text Editor- en mode pleine page, l'insertion d'image ne fonctionne pas
  packages/modul-components/src/components/rich-text-editor/rte-internal.scss
Labels: bug fix

#206 [m-rich-text-editor] Figer la version de froala-editor pour éviter les mises à jour surprises
  packages/modul-components/package.json
  yarn.lock
Labels: bug fix

#197 Retirer le z-index des options par défauts du MRichTextEditor
  packages/modul-components/src/components/rich-text-editor/rich-text-editor-options.ts
Labels: bug fix

#196 Add label & placeholder props to address-lookup-field component
  packages/modul-components/src/components/address/address-lookup-field/address-lookup-field.html
  packages/modul-components/src/components/address/address-lookup-field/address-lookup-field.scss
  packages/modul-components/src/components/address/address-lookup-field/address-lookup-field.ts
Labels: enhancement

#207 [m-portal] Émettre à nouveau un événement update: et gérer les stackIndex à 0
  packages/modul-components/src/components/popup/popup.html
  packages/modul-components/src/components/popup/popup.ts
  packages/modul-components/src/mixins/portal/portal.ts
  packages/modul-components/src/utils/modul/modul.ts
Labels: bug fix

#198 Froala, bouton des caractères spéciaux
  packages/modul-components/src/assets/icons/svg/Froala-special-charracters.svg
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.scss
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.ts
Labels: bug fix

#218 [m-file-upload] Feature/ena2 9567 file upload ajouter custom validation fct
  packages/modul-components/src/components/file-select/file-select.spec.ts
  packages/modul-components/src/components/file-select/file-select.ts
  packages/modul-components/src/components/file-upload/file-upload.html
  packages/modul-components/src/components/file-upload/file-upload.spec.ts
  packages/modul-components/src/components/file-upload/file-upload.ts
  packages/modul-components/src/utils/file/file.spec.ts
  packages/modul-components/src/utils/file/file.ts
  src/modul-website/public/content/components/file-upload/file-upload.overview.fr.md
  src/storybook/src/modul-components/components/file-upload/__snapshots__/file-upload.stories.ts.snap
  src/storybook/src/modul-components/components/file-upload/file-upload.stories.ts
Labels: enhancement

#230 MMultiSelect : Ajout du Placehoder dans le multi-select
  packages/modul-components/src/components/multi-select/multi-select.html
  packages/modul-components/src/components/multi-select/multi-select.ts
  src/storybook/src/modul-components/components/form/__snapshots__/form.all-fields.stories.ts.snap
  src/storybook/src/modul-components/components/multi-select/__snapshots__/multi-select.stories.ts.snap
  src/storybook/src/modul-components/components/multi-select/multi-select.stories.ts
Labels: enhancement

#223 Bugfix/font fallback importation
  packages/modul-components/src/styles/font/_font.scss
  packages/modul-components/src/styles/mixins/_typography.scss
Labels: bug fix

#227 [i18n] Feature/i18n pluralization negative numbers
  packages/modul-components/src/utils/i18n/i18n.spec.ts
  packages/modul-components/src/utils/i18n/i18n.ts
Labels: enhancement

#228 ENA2-9651 - ajouter fonction custom pour valider image rich text
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.html
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.ts
  packages/modul-components/src/components/rich-text-editor/rich-text-editor.html
  packages/modul-components/src/components/rich-text-editor/rich-text-editor.ts
  src/storybook/src/modul-components/components/rich-text-editor/rich-text-editor.sandbox.html
  src/storybook/src/modul-components/components/rich-text-editor/rich-text-editor.sandbox.ts
Labels: enhancement

#161 [m-dropdown] Changer valeur par défaut props
  packages/modul-components/src/components/dropdown/dropdown.ts
  src/storybook/src/modul-components/components/dropdown/__snapshots__/dropdown.stories.ts.snap
  src/storybook/src/modul-components/components/dropdown/dropdown.stories.ts
Labels: enhancement, next

#232 [m-searchfield] Ajout événement emptyField sur le searchfield
  packages/modul-components/src/components/searchfield/searchfield.ts
  src/storybook/src/modul-components/components/searchfield/__snapshots__/searchfield.stories.ts.snap
  src/storybook/src/modul-components/components/searchfield/searchfield.stories.ts
Labels: enhancement

#234 [m-rich-text-editor] ENA2-8914 - RTE : les options alignement, souligné et barré sont perdues lors du copier/coller
  packages/modul-components/src/components/rich-text-editor/rich-text-editor-options.ts
Labels: bug fix
