Repository ulaval/modul, pull requests merged in 2020-11, with the labels that each got.

#430 [m accordion] Reformater le code selon standard (PR1)
  packages/modul-components/src/components/accordion/accordion.html
  packages/modul-components/src/components/accordion/accordion.ts
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-disabled.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-enabled.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-open-all.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-opened-ids.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-secondary-content.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
  src/storybook/src/modul-components/components/accordion/__snapshots__/accordion.stories.ts.snap
  src/storybook/src/modul-components/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
Labels: enhancement

#431 [m-accordeon] Ajuster accessibilité du m-accordeon (PR2)
  packages/modul-components/src/components/accordion/accordion.html
  packages/modul-components/src/components/accordion/accordion.lang.en.json
  packages/modul-components/src/components/accordion/accordion.lang.fr.json
  packages/modul-components/src/components/accordion/accordion.ts
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-disabled.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-enabled.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-open-all.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-opened-ids.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-secondary-content.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
  src/storybook/src/modul-components/components/accordion/__snapshots__/accordion.stories.ts.snap
  src/storybook/src/modul-components/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
Labels: enhancement

#433 [m multi-select] Supporter la prop Options à undefined
  packages/modul-components/src/components/multi-select/multi-select.ts
  src/storybook/src/modul-components/components/multi-select/__snapshots__/multi-select.stories.ts.snap
  src/storybook/src/modul-components/components/multi-select/multi-select.stories.ts
Labels: bug fix

#440 [m-file-upload] - Espace insecable file upload
  packages/modul-components/src/components/file-upload/file-upload.html
  packages/modul-components/src/components/file-upload/file-upload.lang.fr.json
  packages/modul-components/src/components/i18n/i18n.ts
Labels: bug fix

#441 [m-breadcrumbs] mauvaise déclaration des sous composant
  packages/modul-components/src/components/breadcrumbs/breadcrumbs.html
  packages/modul-components/src/components/breadcrumbs/breadcrumbs.ts
Labels: bug fix

#439 [m accordion] accessibilite
  packages/modul-components/src/components/accordion/accordion.html
  packages/modul-components/src/components/accordion/accordion.lang.en.json
  packages/modul-components/src/components/accordion/accordion.lang.fr.json
  packages/modul-components/src/components/accordion/accordion.ts
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-disabled.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-enabled.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-open-all.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-opened-ids.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group-secondary-content.stories.ts.snap
  src/storybook/src/modul-components/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
  src/storybook/src/modul-components/components/accordion/__snapshots__/accordion.stories.ts.snap
  src/storybook/src/modul-components/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
Labels: Accessibility

#443 [m-periodpicker] toIsoString utilise la donnée "from" au lieu de "to"
  packages/modul-components/src/components/periodpicker/periodpicker.ts
Labels: bug fix

#445 [m-datepicker] [m-timepicker] probleme init datepicker timepicker
  packages/modul-components/src/components/datepicker/datepicker.ts
  packages/modul-components/src/components/timepicker/timepicker.ts
  src/storybook/src/modul-components/components/datepicker/__snapshots__/datepicker.stories.ts.snap
  src/storybook/src/modul-components/components/form/__snapshots__/form.all-fields.stories.ts.snap
  src/storybook/src/modul-components/components/form/__snapshots__/form.validators.stories.ts.snap
Labels: bug fix
