Repository ulaval/modul, pull requests merged in 2020-05, with the labels that each got.

#302 [m-modal]Refactor modal (ajout variable css)
  packages/modul-components/src/components/modal/modal.html
  packages/modul-components/src/components/modal/modal.scss
  packages/modul-components/src/components/modal/modal.ts
  src/storybook/src/modul-components/components/modal/__snapshots__/modal.stories.ts.snap
  src/storybook/src/modul-components/components/modal/modal-stories.scss
  src/storybook/src/modul-components/components/modal/modal.stories.ts
Labels: enhancement

#299 [m-menu] Feature/refactor menu (Ajout variable css)
  packages/modul-components/src/components/input-style/input-style.scss
  packages/modul-components/src/components/menu/menu-item/menu-item.html
  packages/modul-components/src/components/menu/menu-item/menu-item.scss
  packages/modul-components/src/components/menu/menu-item/menu-item.ts
  packages/modul-components/src/components/menu/menu.html
  packages/modul-components/src/components/menu/menu.scss
  packages/modul-components/src/components/menu/menu.ts
  packages/modul-components/src/components/searchfield/searchfield.scss
  src/storybook/src/modul-components/components/menu/__snapshots__/menu.stories.ts.snap
  src/storybook/src/modul-components/components/menu/menu.stories.scss
  src/storybook/src/modul-components/components/menu/menu.stories.ts
  src/storybook/src/modul-components/components/searchfield/searchfield.stories.scss
  src/storybook/src/modul-components/components/textfield/textfield.stories.scss
Labels: enhancement

#301 [m-phonefield] Retirer les traductions de pays de la liste déroulante
  packages/modul-components/src/components/phonefield/assets/all-countries-en.ts
  packages/modul-components/src/components/phonefield/assets/all-countries-fr.ts
Labels: enhancement, visual breaking change

#304 [m-postalcodefield] - Modifier le zip code USA
  packages/modul-components/src/components/postalcodefield/postalcodefield.ts
  src/storybook/src/modul-components/components/postalcodefield/postalcodefield.stories.ts
Labels: bug fix

#306 [m-select] Corrections focus, slots et emit
  packages/modul-components/src/components/phonefield/phonefield.html
  packages/modul-components/src/components/phonefield/phonefield.ts
  packages/modul-components/src/components/select/base-select/base-select.html
  packages/modul-components/src/components/select/base-select/base-select.ts
  packages/modul-components/src/components/select/select.html
  packages/modul-components/src/components/select/select.ts
  src/storybook/src/modul-components/components/phonefield/__snapshots__/phonefield.stories.ts.snap
  src/storybook/src/modul-components/components/select/__snapshots__/select.stories.ts.snap
  src/storybook/src/modul-components/components/select/select.stories.ts
Labels: bug fix

#309 [m-rich-text-editor] Remove inline style attribute from svg (CSP compliant)
  packages/modul-components/src/components/rich-text-editor/adapter/image-layout-commands.ts
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.ts
  packages/modul-components/src/components/rich-text-editor/svg/Froala-04.svg
  packages/modul-components/src/components/rich-text-editor/svg/Froala-bold.svg
  packages/modul-components/src/components/rich-text-editor/svg/Froala-image-block-center.svg
  packages/modul-components/src/components/rich-text-editor/svg/Froala-image-block-left.svg
  packages/modul-components/src/components/rich-text-editor/svg/Froala-image-float-left.svg
  packages/modul-components/src/components/rich-text-editor/svg/Froala-image-float-right.svg
  packages/modul-components/src/components/rich-text-editor/svg/Froala-lists.svg
  packages/modul-components/src/components/rich-text-editor/svg/Froala-replace.svg
  packages/modul-components/src/components/rich-text-editor/svg/Froala-special-charracters.svg
  packages/modul-components/src/components/rich-text-editor/svg/Froala-styles.svg
  packages/modul-components/src/components/rich-text-editor/svg/Froala-title.svg
Labels: enhancement

#313 [m-rich-text-editor] copy svg to dist
  packages/modul-components/package.json
Labels: bug fix

#314 [m-select] Hotfix/add prevent modifier to space event
  packages/modul-components/src/components/multi-select/multi-select.html
  packages/modul-components/src/components/select/select.html
Labels: enhancement

#318 [m-select] - Ajouter width et max-width au m-select
  packages/modul-components/src/components/multi-select/multi-select.html
  packages/modul-components/src/components/phonefield/phonefield.html
  packages/modul-components/src/components/phonefield/phonefield.ts
  packages/modul-components/src/components/select/base-select/base-select.html
  packages/modul-components/src/components/select/base-select/base-select.scss
  packages/modul-components/src/components/select/base-select/base-select.ts
  packages/modul-components/src/components/select/select.html
  packages/modul-components/src/components/select/select.ts
  src/storybook/src/modul-components/components/form/__snapshots__/form.all-fields.stories.ts.snap
  src/storybook/src/modul-components/components/form/sandboxes/form-complex.sandbox.html
  src/storybook/src/modul-components/components/form/sandboxes/form-complex.sandbox.ts
  src/storybook/src/modul-components/components/multi-select/__snapshots__/multi-select.stories.ts.snap
  src/storybook/src/modul-components/components/multi-select/multi-select.stories.ts
  src/storybook/src/modul-components/components/phonefield/__snapshots__/phonefield.stories.ts.snap
  src/storybook/src/modul-components/components/phonefield/phonefield.stories.ts
  src/storybook/src/modul-components/components/select-virtual-scroll/__snapshots__/select-virtual-scroll.stories.ts.snap
  src/storybook/src/modul-components/components/select/__snapshots__/select.stories.ts.snap
  src/storybook/src/modul-components/components/select/select.stories.ts
  src/storybook/src/modul-components/components/typeahead/__snapshots__/typeahead.stories.ts.snap
Labels: bug fix, enhancement

#321 Feature/ena2 11084 ajout filtre code postal
  packages/modul-components/src/components/postalcodefield/postalcodefield.ts
  packages/modul-components/src/filters/filter-names.ts
  packages/modul-components/src/filters/postal-code/postal-code.ts
  src/storybook/src/modul-components/filters/postal-code/__snapshots__/postal-code.stories.ts.snap
  src/storybook/src/modul-components/filters/postal-code/postal-code.stories.ts
Labels: new feature

#323 [m-dialog] Déplacer l'enregistrement du service $dialog
  packages/modul-components/src/components/dialog/dialog.ts
  packages/modul-components/src/utils/dialog/dialog-service.plugin.ts
  packages/modul-components/src/utils/dialog/dialog-service.ts
  src/storybook/src/modul-components/components/dialog/__snapshots__/dialog.sandbox.stories.ts.snap
  src/storybook/src/modul-components/components/dialog/dialog.sandbox.stories.ts
  src/storybook/src/modul-components/components/dialog/sandboxes/dialog-service.sandbox.html
  src/storybook/src/modul-components/components/dialog/sandboxes/dialog-service.sandbox.ts
Labels: enhancement

#305 m-checkbox: ajouter la prop "hiddenLabel: string"
  packages/modul-components/src/components/accordion/accordion.spec.ts
  packages/modul-components/src/components/checkbox/checkbox.html
  packages/modul-components/src/components/checkbox/checkbox.scss
  packages/modul-components/src/components/checkbox/checkbox.ts
  packages/modul-components/src/components/phonefield/phonefield.html
  packages/modul-components/src/mixins/input-width/input-width.ts
  src/storybook/src/modul-components/components/checkbox/__snapshots__/checkbox.stories.ts.snap
  src/storybook/src/modul-components/components/checkbox/checkbox.stories.ts
  src/storybook/src/modul-components/components/datepicker/__snapshots__/datepicker.stories.ts.snap
  src/storybook/src/modul-components/components/form/__snapshots__/form.all-fields.stories.ts.snap
  src/storybook/src/modul-components/components/form/__snapshots__/form.rules.stories.ts.snap
  src/storybook/src/modul-components/components/input-group/__snapshots__/input-group.stories.ts.snap
  src/storybook/src/modul-components/components/table/__snapshots__/table.stories.ts.snap
Labels: enhancement

#308 [m-spinner] Ajuster l'espace entre les texte du spinner et améliorer sa réactivité en mode processing
  packages/modul-components/src/components/spinner/spinner.html
  packages/modul-components/src/components/spinner/spinner.scss
  packages/modul-components/src/components/spinner/spinner.ts
  src/storybook/src/modul-components/components/spinner/__snapshots__/spinner.stories.ts.snap
  src/storybook/src/modul-components/components/spinner/spinner.stories.ts
Labels: bug fix

#320 [m-phonefield] - Remettre code de pays comme préfix
  packages/modul-components/src/components/phonefield/assets/all-countries-en.ts
  packages/modul-components/src/components/phonefield/assets/all-countries-fr.ts
  packages/modul-components/src/components/phonefield/phonefield.html
  packages/modul-components/src/components/phonefield/phonefield.scss
  packages/modul-components/src/components/phonefield/phonefield.ts
  src/storybook/src/modul-components/components/phonefield/__snapshots__/phonefield.stories.ts.snap
  src/storybook/src/modul-components/components/phonefield/phonefield.stories.ts
Labels: enhancement

#322 [core] Permettre l'utilisation des composantes MODUL "à-la-demande" pour la version distribuer
  packages/modul-components/.gitignore
  packages/modul-components/.npmignore
  packages/modul-components/conf/webpack.lib.js
  packages/modul-components/package.json
  packages/modul-components/src/components/components-plugin.ts
  packages/modul-components/src/components/decimalfield/decimalfield.ts
  packages/modul-components/src/components/phonefield/phonefield.ts
  packages/modul-components/src/directives/directives-plugin.ts
  packages/modul-components/src/lib.ts
  src/modul-website/public/content/components/expandable-layout/expandable-layout.preview.fr.md
  src/modul-website/src/modul.ts
  yarn.lock
Labels: enhancement, next

#327 Misc/ajout des composantes manquantes a distribution
  packages/modul-components/src/components/rich-text-editor/rich-text-editor.ts
  packages/modul-components/src/components/rich-text-editor/rich-text-license-plugin.ts
  packages/modul-components/src/components/spinner/spinner.ts
  packages/modul-components/src/lib.ts
  packages/modul-components/src/utils/dialog/dialog-service.ts
Labels: breaking change, next

#310 [element-query] Update css-element-queries dependency
  packages/modul-components/package.json
  packages/modul-components/src/components/limit-text/limit-text.spec.ts
  packages/modul-components/src/components/navbar/navbar-item/navbar-item.spec.ts
  packages/modul-components/src/components/navbar/navbar.spec.ts
  packages/modul-components/src/components/rich-text-editor/adapter/vue-froala.spec.ts
  packages/modul-components/src/components/rich-text-editor/rich-text-editor.spec.ts
  packages/modul-components/src/components/textarea/textarea.spec.ts
  packages/modul-components/src/mixins/element-queries/element-queries.ts
  packages/modul-components/tests/helpers/mock-resizeSensor.ts
  src/storybook/src/modul-components/components/form/__snapshots__/form.all-fields.stories.ts.snap
  src/storybook/src/modul-components/components/navbar/__snapshots__/navbar.stories.ts.snap
  src/storybook/src/modul-components/components/steppers/__snapshots__/steppers.stories.ts.snap
  src/storybook/src/modul-components/components/transitions/slide-transition/__snapshots__/slide-transition.stories.ts.snap
  yarn.lock
Labels: enhancement

#329 [m-postalcodefield] Changé la casse des codes de pays
  packages/modul-components/src/components/postalcodefield/postalcodefield.ts
  packages/modul-components/src/filters/postal-code/postal-code.ts
  src/storybook/src/modul-components/components/postalcodefield/__snapshots__/postalcodefield.stories.ts.snap
  src/storybook/src/modul-components/filters/postal-code/__snapshots__/postal-code.stories.ts.snap
Labels: bug fix

#333 [m-dialog-service] Résoudre la promesse sur le clique du bouton secondaire
  packages/modul-components/src/utils/dialog/dialog-service.ts
  src/storybook/src/modul-components/components/dialog/sandboxes/dialog-service.sandbox.html
  src/storybook/src/modul-components/components/dialog/sandboxes/dialog-service.sandbox.ts
Labels: bug fix

#331 Rendre compatible le composant progress pour le Content-Security-Policy
  packages/modul-components/src/components/progress/progress.ts
  packages/modul-components/src/utils/modul/modul.ts
  packages/modul-components/src/utils/utils-plugin.ts
Labels: enhancement
